# Generated by Django 4.1.6 on 2023-02-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="favorite_of_authors",
                to="main.post",
            ),
        ),
    ]
