# Generated by Django 4.1.6 on 2023-02-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_author_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="post_set", to="main.tag"
            ),
        ),
    ]
