# Generated by Django 4.1.7 on 2023-03-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_author_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="author_pics/default1.png",
                null=True,
                upload_to="author_pics",
            ),
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="liked_posts", to="main.author"
            ),
        ),
    ]
