# Generated by Django 4.1.6 on 2023-02-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_category_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="author_pics"),
        ),
    ]
