# Generated by Django 4.1.7 on 2023-03-22 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_author_profile_pic_remove_post_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="dob",
            field=models.DateField(default=datetime.date(2023, 3, 22)),
        ),
    ]
