# Generated by Django 4.1.7 on 2023-04-13 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_author_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="following",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="followers", to="main.author"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="dob",
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
    ]
