# Generated by Django 4.1.7 on 2023-08-25 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_author_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="dob",
            field=models.DateField(default=datetime.date(2023, 8, 25), null=True),
        ),
    ]
