# Generated by Django 4.1.7 on 2023-08-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_author_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
